[package]
name = "versionitis"
version = "0.1.0"
authors = ["jonathan gerber <jlgerber@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_yaml = "0.8.8"
pest = "2.1.0"
pest_derive = "2.1.0"

[dev-dependencies]
batsat = "0.3"
